import { VscLibrary } from "react-icons/vsc";
import { FaArrowRightLong  } from "react-icons/fa6";
import { GoServer } from "react-icons/go";

import { FiPlus } from "react-icons/fi";

const CompEight = () => {
  return (
    <div className="w-full">
        <div className="w-full md:w-4/6 flex flex-col gap-5 p-10">
            <div className=" p-3 w-fit rounded-2xl bg-blue-800/16">
                <GoServer size={40} className="text-blue-500"/>
                <FiPlus />
            </div>
                <h1 className="text-3xl md:text-5xl font-semibold">Components, meet the Utility API</h1>
                <p className="md:text-lg  tracking-wide">New in Bootstrap 5, our utilities are now generated by our Utility API. We built it as a feature-packed Sass map that can be quickly and easily customized. It's never been easier to add, remove, or modify any utility classes. Make utilities responsive, add pseudo-class variants, and give them custom names.</p>
        </div>
    </div>
  )
}

export default CompEight