

const HeroComponent = () => {
  return (
<div className=" md:w-[60%] h-fit bg-blue-600 sticky px-5">
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum voluptatem eligendi qui cumque tempora corrupti temporibus itaque mollitia officiis minus? Ipsa vel tempore obcaecati atque, ullam vitae fugit ad aspernatur?</p>
      </div>
  );
};

export default HeroComponent;

